# Generated by Django 4.2.7 on 2023-12-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
                ('habilidad', models.CharField(max_length=30)),
                ('debilidad', models.CharField(max_length=30)),
            ],
        ),
    ]
