# Generated by Django 4.2.7 on 2023-12-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
    ]
